import = [
    "~/.config/alacritty/themes/themes/solarized_dark.toml"
]

[font]
size = 14.0

[font.normal]
family = "Hack Nerd Font"

[window]
decorations = "Full"
opacity = 0.9
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 140
lines = 50

[scrolling]
history = 50000
